### ISSUE TITLE
missing field `_version` at line 1 column 1189

### ISSUE THREAD

**Issue by alibouaziz** [CanalTP/mimirsbrunn#387]
when run:
```bash
bano2mimir --input=/data/addresses/bano.csv --connection-string=http://elasticsearch:9200 --nb-threads --nb-shards --nb-replicas --dataset=default
```
i get:
ERRO failed to bulk insert: missing field `_version` at line 1 column 1189
ERRO missing field `_version` at line 1 column 1189

Thanks :)

**Comment by antoine-de** [comment]
are you sure to have the right ES version (`2.x`)? I haven't used this for a while but I think I had this problem when using a newer ES version.

**Comment by alibouaziz** [comment]
yes, 2.4.6
![image](https://user-images.githubusercontent.com/24412687/80370071-3d61bf00-8887-11ea-9460-ff4be4ab3832.png)

**Comment by antoine-de** [comment]
oh, sorry then, I'll let the team answer your question.

maybe you can add the creation date of the bano files used for them to be able to reproduce the issue?

**Comment by alibouaziz** [comment]
osm.url: https://download.geofabrik.de/europe/france-latest.osm.pbf => 2020-04-27 02:14 | 3.6G
addresses.bano.url: https://bano.openstreetmap.fr/data/full.csv.gz  => 27-Apr-2020 03:56 | 204M

**Comment by riendegris** [comment]
Hello,

if i understand correctly, you downloaded the bano file `data.full.csv.gz` and then unzip it to `bano.csv`, started a docker, and called bano2mimir with the command line described above, correct?

**Comment by alibouaziz** [comment]
yes :)

**Comment by riendegris** [comment]
puzzling... i did not manage to reproduce your error. My run just completed with the following logs:

```
Apr 27 16:48:59.108 WARN Address addr:2.187688;48.825852:9 has no street name and has been ignored.
Apr 27 16:48:59.108 WARN Address addr:2.178053;48.821247:99 has no street name and has been ignored.
Apr 27 16:51:27.742 INFO importing addresses: 16790227 addresses added.
Apr 27 16:51:27.742 INFO Doing post_op on /munin_addr_default_20200427_141039_954978557/_refresh
Apr 27 16:51:27.951 INFO for munin_addr_default, adding alias ["munin_addr_default_20200427_141039_954978557"], removing []
Apr 27 16:51:27.977 INFO for munin_addr, adding alias ["munin_addr_default"], removing []
Apr 27 16:51:28.001 INFO for munin_geo_data, adding alias ["munin_addr"], removing []
Apr 27 16:51:28.019 INFO for munin, adding alias ["munin_geo_data"], removing []
Apr 27 16:51:28.037 INFO Addresses imported per country:
Apr 27 16:51:28.037 INFO         fr 16790227
```

Now it took a while to run (and discover no error) so I suggest the following to help me:

what's your os / distribution / version
what's the version of rust you're using (rustc --version)
what's the version of mimirsbrunn you're using
docker image is 'elasticsearch:2'
make a small script with a small dataset (eg one departement) that i can run and still reproduce the error

**Comment by alibouaziz** [comment]
thank you,
ubuntu 18.04,
i use [docker_mimir](https://github.com/QwantResearch/docker_mimir)
so all things inside containers

**Comment by amatissart** [comment]
This error `ERRO missing field _version at line 1 column 1189` shows that rs-es (the library we are using to interact with Elasticsearch) failed to parse the response of the bulk request.

As your configuration looks good, it may be due to a network issue or too high load on your machine.
Is the error occurring as soon as you run the command, of after some time ? 
Any other log messages beforehand ?
Maybe you could try to set a lower number of threads explicitly with `--nb-threads` (the number of cpus is used by default).

**Comment by alibouaziz** [comment]
this is my docker_settings.yml
```yaml
# example file to run mimir in docker

es: http://35.226.152.43:80

osm:
  url: https://download.geofabrik.de/europe/france-latest.osm.pbf

admin:
  cosmogony:
    output_dir: /data/cosmogony
    langs: "fr,en,de"

street:
  osm_db_file: /data/osm/osm_db.tmp

poi:
  osm:

addresses:
  use_deduplicator: false
  skip_deduplication: true
  bano:
    url: https://bano.openstreetmap.fr/data/full.csv.gz
  oa:
    url: https://data.openaddresses.io/openaddr-collected-europe.zip
    include:
      - fr/**.csv

geocoder_tester_region: france
```
